<!-- Load Facebook SDK for JavaScript -->
<?php
$helper = $this->helper('Lof\FacebookChat\Helper\Data');
$enable = $helper->getConfig('general_settings/enable');
$page_id = $helper->getConfig('general_settings/page_id');
$appId = $helper->getConfig('general_settings/app_id');
$theme_color = $helper->getConfig('general_settings/theme_color');
$logged_in_greeting = $helper->getConfig('general_settings/logged_in_greeting');
$logged_out_greeting = $helper->getConfig('general_settings/logged_out_greeting');
$language = $helper->getConfig('general_settings/language');

if($enable && $page_id && $appId) {
?>
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId            : '<?php echo $appId;?>',
      autoLogAppEvents : true,
      xfbml            : true,
      version          : 'v3.3'
    });
  };

  (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/<?php echo $language; ?>/sdk/xfbml.customerchat.js';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<!-- Your customer chat code -->
<div class="fb-customerchat"
  attribution=setup_tool
  page_id="<?php echo $page_id; ?>"
  theme_color="<?php echo $theme_color; ?>"
  logged_in_greeting="<?php echo $logged_in_greeting; ?>"
  logged_out_greeting="<?php echo $logged_out_greeting; ?>">
</div>
<?php } ?>